challenges/urls.py
from django.urls import path
from . import views

app_name = 'challenges'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:month>', views.monthly_challenges_number, name="monthly_challenges_number"),
    path('<str:month>', views.monthly_challenges, name="monthly_challenges"),
]

monthly_challenges/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('challenges/', include('challenges.urls')),
]

challenges/models.py
from django.db import models

# Create your models here.

challenges/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse

from django.template.loader import render_to_string

month_dictionary = {
    'january': "Focus on being productive instead of busy.",
    'february': "Do the hard jobs first. The easy jobs will take care of themselves.",
    'march': "Productivity is being able to do things that you were never able to do before.",
    'april': "It's not always that we need to do more but rather that we need to focus on less.",
    'may': "My goal is no longer to get more done, but rather to have less to do.",
    'june': "You can fool everyone else, but you can't fool your own mind.",
    'july': "You miss 100% of the shots you don't take.",
    'august': "Simplicity boils down to two steps: Identify the essential. Eliminate the rest.",
    'september': "Strive not to be success, but rather to be of value.",
    'october': "Sometimes, things may not go to your way, but the effort should be there every single night.",
    'november': "The way to get started is to quit talking and begin doing.",
    'december': None
    # 'december': "If you spend to much time thinking about a thing, you'll never get it done."
}


# Create your views here.
def index(request):
    months = list(month_dictionary.keys())

    return render(request, 'challenges/index.html', {
        'head_title': "All Challenges",
        'months': months
    })


def monthly_challenges(request, month):
    try:
        month_quote = month_dictionary[month]
        response_data = f"<h1>{month_quote}</h1>"
    except:
        print("Invalid Month")
    else:
        return render(request, 'challenges/challenge.html', {
            'head_title': "Monthly Challenges",
            'month': month,
            'quote': month_quote
        })


def monthly_challenges_number(request, month):
    if month >= 1 and month <= 12:
        month = (list(month_dictionary.keys()))[month - 1]
        return HttpResponseRedirect(reverse("challenges:monthly_challenges", args=[month]))
    else:
        return render(request, '404.html', {
            'head_nav': "There something went wrong",
            'message': "Page not Found",
            'description': "Sorry, we could not process your request. It looks like you have entered an invalid month."
        })

challenges/templates/challenges/challenge.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'challenges/includes/header.css' %}">
    <link rel="stylesheet" href="{% static 'challenges/challenge.css' %}">
    <link rel="stylesheet" href="{% static 'challenges/challenges.css' %}">
{% endblock %}

{% block body %}
    {% include 'challenges/includes/header.html' with active_page="monthly_challenges" %}

    <h1>This Month of {{ month|title }} Challenge</h1>
    {% if quote is not None %}
        <h2>{{ quote }}</h2>
    {% else %}
        <h2>There is no quote in this month of {{ month }}.</h2>
    {% endif %}
{% endblock %}

challenges/templates/challenges/includes/header.html
<!DOCTYPE html>

<nav>
    <a href="{% url 'challenges:index' %}">All Challenges</a>
</nav>

challenges/templates/challenges/index.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'challenges/includes/header.css' %}">
    <link rel="stylesheet" href="{% static 'challenges/challenge.css' %}">
{% endblock %}

{% block body %}
    {% include 'challenges/includes/header.html' with active_page="index" %}

    <ul>
        {% for month in months %}
            <li><a href="{% url 'challenges:monthly_challenges' month %}">{{ month|title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ head_title }}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block css %}
    {% endblock %}
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>